FROM dhi.io/node:26-alpine3.24-dev AS builder

WORKDIR /app

RUN --mount=type=cache,target=/root/.npm \
    --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    npm ci

# Copy the source code into the container and compile TypeScript.
COPY . .
RUN npm run build:frontend:prod

FROM lipanski/docker-static-website:2.6.0

# serve index.html in place of missing files (single page app)
COPY <<EOF httpd.conf
E404:index.html
EOF

# override command line to use our custom config
# see: https://github.com/lipanski/docker-static-website/issues/39
CMD ["/busybox-httpd", "-f", "-v", "-p", "3000", "-c", "httpd.conf"]

COPY --from=builder /app/dist/web /home/static
